# Generated by Django 2.0.6 on 2019-11-12 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Balance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exposure', models.FloatField(null=True)),
                ('balance', models.FloatField(null=True)),
                ('free_funds', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bet_id', models.BigIntegerField(null=True)),
                ('trade', models.FloatField(null=True)),
                ('back', models.FloatField(null=True)),
                ('lay', models.FloatField(null=True)),
                ('margin', models.FloatField(null=True)),
                ('bracket', models.IntegerField(null=True)),
                ('payout', models.FloatField(null=True)),
                ('liability', models.FloatField(null=True)),
                ('order_type', models.CharField(max_length=50)),
                ('persistence_type', models.CharField(max_length=50)),
                ('placed_at', models.DateTimeField()),
                ('price', models.FloatField(null=True)),
                ('size', models.FloatField(null=True)),
                ('side', models.CharField(max_length=20)),
                ('size_matched', models.FloatField(null=True)),
                ('size_remaining', models.FloatField(null=True)),
                ('size_lapsed', models.FloatField(null=True)),
                ('size_cancelled', models.FloatField(null=True)),
                ('size_voided', models.FloatField(null=True)),
                ('status', models.CharField(max_length=30)),
                ('outcome', models.CharField(max_length=50, null=True)),
                ('profit', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('bet_delay', models.FloatField(null=True)),
                ('inplay', models.BooleanField()),
                ('number_of_winners', models.IntegerField(null=True)),
                ('number_of_runners', models.IntegerField(null=True)),
                ('total_matched', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_name', models.CharField(max_length=15)),
                ('event_id', models.BigIntegerField(unique=True)),
                ('event_name', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=13)),
            ],
        ),
        migrations.CreateModel(
            name='EventMonitor',
            fields=[
                ('sport', models.CharField(max_length=50, null=True)),
                ('country', models.CharField(max_length=50, null=True)),
                ('live', models.CharField(max_length=50, null=True)),
                ('stage', models.CharField(max_length=50, null=True)),
                ('event_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('open_date', models.CharField(max_length=50, null=True)),
                ('cat_name', models.CharField(max_length=50, null=True)),
                ('market_type', models.CharField(max_length=50, null=True)),
                ('status', models.CharField(max_length=13, null=True)),
                ('is_ip', models.CharField(max_length=10, null=True)),
                ('competition', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, null=True)),
                ('password', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.BigIntegerField(unique=True)),
                ('market_name', models.CharField(max_length=35)),
                ('status', models.CharField(max_length=10)),
                ('volume', models.FloatField(null=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apimb.Event')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('market_id', models.BigIntegerField(null=True)),
                ('temp_id', models.CharField(max_length=20, null=True)),
                ('event_name', models.CharField(max_length=200, null=True)),
                ('time_stamp', models.DateTimeField(null=True)),
                ('event_id', models.BigIntegerField(null=True)),
                ('market_name', models.CharField(max_length=12, null=True)),
                ('market_type', models.CharField(max_length=13, null=True)),
                ('runner_id', models.BigIntegerField(null=True)),
                ('runner_name', models.CharField(max_length=100, null=True)),
                ('side', models.CharField(max_length=9, null=True)),
                ('odds', models.FloatField(null=True)),
                ('odds_type', models.CharField(max_length=20, null=True)),
                ('stake', models.IntegerField(null=True)),
                ('remaining', models.IntegerField(null=True)),
                ('pot_pro', models.IntegerField(null=True)),
                ('rem_pot_pro', models.IntegerField(null=True)),
                ('pot_lib', models.IntegerField(null=True)),
                ('created_at', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=40, null=True)),
                ('inplay', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_id', models.BigIntegerField(unique=True)),
                ('event_id', models.BigIntegerField(null=True)),
                ('name', models.CharField(max_length=100)),
                ('market', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='apimb.Market')),
            ],
        ),
        migrations.CreateModel(
            name='RunnerBook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=20)),
                ('last_price_traded', models.FloatField(null=True)),
                ('total_matched', models.FloatField(null=True)),
                ('back_price', models.FloatField(null=True)),
                ('back_size', models.FloatField(null=True)),
                ('lay_price', models.FloatField(null=True)),
                ('lay_size', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_bal', models.FloatField(null=True)),
                ('percent_1', models.FloatField(null=True)),
                ('percent_2', models.FloatField(null=True)),
                ('percent_3', models.FloatField(null=True)),
                ('percent_4', models.FloatField(null=True)),
                ('percent_5', models.FloatField(null=True)),
                ('percent_10', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserStakes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('back_stake', models.IntegerField(blank=True)),
                ('lay_stake', models.IntegerField(blank=True)),
            ],
        ),
    ]
