# Generated by Django 2.0.6 on 2019-11-12 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0002_auto_20191112_0845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='sport_name',
            new_name='sport_id',
        ),
    ]
