# Generated by Django 2.0.6 on 2019-11-12 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0003_auto_20191112_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='market',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='apimb.Market'),
        ),
    ]
