# Generated by Django 2.0.6 on 2019-11-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0005_remove_runner_event_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='percent_1',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_10',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_2',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_3',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_4',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_5',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_6',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_7',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_8',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='balance',
            name='percent_9',
            field=models.FloatField(null=True),
        ),
    ]
