# Generated by Django 2.0.6 on 2019-11-15 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0006_auto_20191115_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='round_bal',
            field=models.IntegerField(null=True),
        ),
    ]
