# Generated by Django 2.0.6 on 2019-11-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0007_balance_round_bal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='name',
            field=models.CharField(max_length=500),
        ),
    ]
