# Generated by Django 2.0.6 on 2019-11-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0008_auto_20191115_1047'),
    ]

    operations = [
        migrations.CreateModel(
            name='BetTriggers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b1_trig', models.FloatField(null=True)),
                ('b2_trig', models.FloatField(null=True)),
                ('l1_trig', models.FloatField(null=True)),
                ('l2_trig', models.FloatField(null=True)),
                ('runner_name', models.CharField(max_length=300)),
                ('runner_id', models.BigIntegerField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='runner_id',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bet',
            name='runner_name',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
