# Generated by Django 2.0.6 on 2019-11-15 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0009_auto_20191115_1142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bettriggers',
            name='b1_trig',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bettriggers',
            name='b2_trig',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bettriggers',
            name='l1_trig',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='bettriggers',
            name='l2_trig',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
