# Generated by Django 2.0.6 on 2019-11-22 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0011_runner_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='runner',
            name='event',
        ),
    ]
