# Generated by Django 2.0.6 on 2019-11-26 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apimb', '0017_sessiontoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportsBets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=50, null=True)),
                ('offer_id', models.CharField(max_length=50, null=True)),
                ('odds', models.CharField(max_length=50, null=True)),
                ('stake', models.CharField(max_length=50, null=True)),
                ('adjusted', models.CharField(max_length=50, null=True)),
                ('originator', models.CharField(max_length=50, null=True)),
                ('inplay', models.CharField(max_length=50, null=True)),
                ('submitted_time', models.CharField(max_length=50, null=True)),
                ('matched_time', models.CharField(max_length=50, null=True)),
                ('settled_time', models.CharField(max_length=50, null=True)),
                ('result', models.CharField(max_length=50, null=True)),
                ('profit_and_loss', models.CharField(max_length=50, null=True)),
                ('commission_type', models.CharField(max_length=50, null=True)),
                ('net_profit_and_loss', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportsMarket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('i_d', models.CharField(max_length=50, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('event_id', models.CharField(max_length=50, null=True)),
                ('event_name', models.CharField(max_length=50, null=True)),
                ('sport_id', models.CharField(max_length=50, null=True)),
                ('start_time', models.CharField(max_length=50, null=True)),
                ('settled_time', models.CharField(max_length=50, null=True)),
                ('stake', models.CharField(max_length=50, null=True)),
                ('commission', models.CharField(max_length=50, null=True)),
                ('profit_and_loss', models.CharField(max_length=50, null=True)),
                ('net_profit_and_loss', models.CharField(max_length=50, null=True)),
                ('selections', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReportsSelections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runner_id', models.CharField(max_length=50, null=True)),
                ('runner_name', models.CharField(max_length=50, null=True)),
                ('side', models.CharField(max_length=50, null=True)),
                ('odds', models.CharField(max_length=50, null=True)),
                ('stake', models.CharField(max_length=50, null=True)),
                ('profit_and_loss', models.CharField(max_length=50, null=True)),
                ('commission', models.CharField(max_length=50, null=True)),
                ('net_profit_and_loss', models.CharField(max_length=50, null=True)),
                ('bets', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
